### ISSUE TITLE
Choose a Language

### ISSUE THREAD

**Issue by jdgiotta** [jdgiotta/thirtyone-game#7]
What language should this game be programmed in?

**Comment by jdgiotta** [comment]
@clenear what language do you want to learn? For ease of use I'd suggest Go or Python, but we can do Java or Node. Your choice.

**Comment by clenear** [comment]
@jdgiotta Let's go with Python

**Comment by jdgiotta** [comment]
> @jdgiotta Let's go with Python

@clenear go ahead and move this card to done in the project columns.
